# Generated by Django 3.2.13 on 2022-06-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addemployees',
            old_name='emp_id',
            new_name='id',
        ),
    ]
